version: "2"

services:
  back-end:
    build:
      context: ./back-end
    image: dmitroderkach/full-stack-course-1-back-end:latest
    restart: always
    environment:
      MONGO_HOST: mongodb://db
      JWT_SECRET: sercet
      LOGDNA_KEY: 7beef7dabe3cc94497fd6148aba2b013
      PORT: 80
    depends_on:
      - db

  front-end:
    build:
      context: ./front-end
    image: dmitroderkach/full-stack-course-1-front-end:latest
    restart: always
    depends_on:
      - back-end
    ports:
      - "80:80"

  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db